language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g webpack
script: npm run build
before_deploy:
  - git add -f public/resources/*
deploy:
  fqdn: 2018.hacksurrey.uk
  provider: pages
  local-dir: public
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
